name: rr
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.2.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  injectable: ^2.5.1
  get_it: ^8.2.0
  flutter_secure_storage: ^9.2.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  go_router_builder: ^3.3.0
  build_runner: ^2.7.0
  json_serializable: ^6.9.4
  injectable_generator: ^2.8.1

flutter:
  uses-material-design: true
